<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9">
  <xsl:output method="html" encoding="UTF-8"/>
  
  <xsl:template match="/">
    <html xmlns="http://www.w3.org/1999/xhtml">
      <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>XML Sitemap</title>
        <style type="text/css">
          body {
          font-family: Helvetica, Arial, sans-serif;
          font-size: 13px;
          color: #545353;
          }
          table {
          border: none;
          border-collapse: collapse;
          width: 100%;
          }
          #sitemap tr:nth-child(odd) td {
          background-color: #eee !important;
          }
          #sitemap tbody tr:hover td {
          background-color: #ccc;
          }
          #sitemap tbody tr:hover td,
          #sitemap tbody tr:hover td a {
          color: #000;
          }
          #content {
          margin: 0 auto;
          width: 1000px;
          }
          .expl {
          margin: 18px 3px;
          line-height: 1.2em;
          }
          .expl a {
          color: #0066cc; /* Blue color */
          font-weight: 600;
          }
          .expl a:visited {
          color: #0066cc; /* Blue color */
          }
          a {
          color: #000;
          text-decoration: none;
          }
          a:visited {
          color: #777;
          }
          a:hover {
          text-decoration: underline;
          }
          th,
          td {
          padding: 10px;
          text-align: left;
          }
          th {
          text-align: left;
          padding-right: 30px;
          font-size: 11px;
          }
          thead th {
          border-bottom: 1px solid #000;
          }
        </style>
      </head>
      <body>
        <div id="content">
          <h1>XML Sitemap</h1>
          <p class="expl"> Generated by <a href="{//generatedBy}" target="_blank" rel="noopener">
              devtitechnologie.com </a>, this is an XML Sitemap, meant for consumption by search
            engines.<br /><br /> You can find more information about XML sitemaps on <a
              href="{//moreInfoURL}" target="_blank" rel="noopener">
              sitemaps.org </a>. </p>
          <p class="expl">This XML Sitemap contains <xsl:value-of select="count(sitemap:urlset/sitemap:url)" /> URLs.</p>
          <table id="sitemap" cellpadding="3">
            <thead>
              <tr>
                <th width="60%">URL</th>
                <th width="15%">Last Modification</th>
                <th width="15%">Change Frequency</th>
                <th width="10%">Priority</th>
              </tr>
            </thead>
            <tbody>
              <xsl:for-each select="//sitemap:urlset/sitemap:url">
                <tr>
                  <td>
                    <a href="{sitemap:loc}">
                      <xsl:value-of select="sitemap:loc" />
                    </a>
                  </td>
                  <td>
                    <xsl:value-of select="sitemap:lastmod" />
                  </td>
                  <td>
                    <xsl:value-of select="sitemap:changefreq" />
                  </td>
                  <td>
                    <xsl:value-of select="sitemap:priority" />
                  </td>
                </tr>
              </xsl:for-each>
            </tbody>
          </table>
        </div>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet>