// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about: dynamic(() => import("./About")),
  about_body: dynamic(() => import("./AboutBody")),
  about_hero: dynamic(() => import("./AboutHero")),
  advantages_cards: dynamic(() => import("./AdvantagesCards")),
  blog_hero: dynamic(() => import("./BlogHero")),
  blogs_list: dynamic(() => import("./BlogsList")),
  brief_of_blogs: dynamic(() => import("./BriefOfBlogs")),
  call_to_action: dynamic(() => import("./CallToAction")),
  chiffres: dynamic(() => import("./Chiffres")),
  contact: dynamic(() => import("./Contact")),
  drop_down_menu: dynamic(() => import("./NavMenus")),
  faq: dynamic(() => import("./Faq")),
  faq_content: dynamic(() => import("./FaqContent")),
  fonctionnalites: dynamic(() => import("./Fonctionnalites")),
  hero_slider: dynamic(() => import("./HeroSlider")),
  image_with_text_col_and_link: dynamic(
    () => import("./ImageWithTextColAndLink"),
  ),
  methode_travaille: dynamic(() => import("./MethodeTravaille")),
  methode_travaille_content: dynamic(() => import("./MethodeTravailleContent")),
  offers_list: dynamic(() => import("./OffersList")),
  our_clients: dynamic(() => import("./OurClients")),
  our_sectors: dynamic(() => import("./OurSectors")),
  portfolio: dynamic(() => import("./Portfolio")),
  realisation_hero: dynamic(() => import("./RealisationHero")),
  realisation_portfolio: dynamic(() => import("./RealisationPortfolio")),
  scroll_down_hero: dynamic(() => import("./ScrollDownHero")),
  service_about: dynamic(() => import("./ServiceAbout")),
  service_call_to_action_form: dynamic(
    () => import("./ServiceCallToActionForm"),
  ),
  service_hero: dynamic(() => import("./ServiceHero")),
  service_reviews: dynamic(() => import("./ServiceReviews")),
  services: dynamic(() => import("./Services")),
  services_cards: dynamic(() => import("./ServicesCards")),
  services_portfolio: dynamic(() => import("./ServicesPortfolio")),
  spacer: dynamic(() => import("./Spacer")),
  terms_content: dynamic(() => import("./TermsContent")),
  unsolicited_job_application_form: dynamic(
    () => import("./UnsolicitedJobApplicationForm"),
  ),
  what_to_gain: dynamic(() => import("./WhatToGain")),
};
